// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.Eshop.Infrastructure.Database;

#nullable disable

namespace UTB.Eshop.Infrastructure.Migrations
{
    [DbContext(typeof(EshopDbContext))]
    [Migration("20231114081216_mysql_1.0.0_init")]
    partial class mysql_100_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UTB.Eshop.Domain.Entities.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Carousels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageAlt = "First slide",
                            ImageSrc = "/img/carousel/how-to-become-an-information-technology-specialist160684886950141.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImageAlt = "Second slide",
                            ImageSrc = "/img/carousel/Information-Technology-1-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImageAlt = "Third slide",
                            ImageSrc = "/img/carousel/itec-index-banner.jpg"
                        });
                });

            modelBuilder.Entity("UTB.Eshop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nejlepší rohlík na světě",
                            ImageSrc = "/img/products/produkty-01.jpg",
                            Name = "Rohlík",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nejlepší chleba v galaxii",
                            ImageSrc = "/img/products/produkty-02.jpg",
                            Name = "Chleba",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nic moc, ale máme ji",
                            ImageSrc = "/img/products/produkty-03.jpg",
                            Name = "Vánočka",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nejlepší bageta ve sluneční soustavě",
                            ImageSrc = "/img/products/produkty-05.jpg",
                            Name = "Bageta",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Každý krogan by bojoval pro tento nejlepší dalamánek ve vesmíru",
                            ImageSrc = "/img/products/produkty-06.jpg",
                            Name = "Dalamánek",
                            Price = 8.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
